2024-07-20 20:58:44,006	WARNING services.py:2010 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67088384 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2024-07-20 20:58:44,120	INFO worker.py:1779 -- Started a local Ray instance. View the dashboard at [1m[32m10.244.9.103:8265 [39m[22m
/root/anaconda3/envs/flybody/lib/python3.10/site-packages/reverb/platform/default/ensure_tf_install.py:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(version) <
/root/anaconda3/envs/flybody/lib/python3.10/site-packages/reverb/platform/default/ensure_tf_install.py:54: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  distutils.version.LooseVersion(required_tensorflow_version)):
2024-07-20 20:58:51.091935: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[36m(ReplayServer pid=2214862)[0m 2024-07-20 20:58:53.754817: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[36m(ReplayServer pid=2214862)[0m [reverb/cc/platform/tfrecord_checkpointer.cc:150]  Initializing TFRecordCheckpointer in /tmp/tmpw6g_c6rx.
[36m(ReplayServer pid=2214862)[0m [reverb/cc/platform/tfrecord_checkpointer.cc:386] Loading latest checkpoint from /tmp/tmpw6g_c6rx
[36m(ReplayServer pid=2214862)[0m [reverb/cc/platform/default/server.cc:71] Started replay server on port 41743
[36m(Learner pid=2215121)[0m 2024-07-20 20:58:56.887068: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
[36m(Learner pid=2215121)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.
[36m(Learner pid=2215121)[0m Instructions for updating:
[36m(Learner pid=2215121)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.
[36m(Learner pid=2215121)[0m 2024-07-20 20:58:57.924079: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
[36m(EnvironmentLoop pid=2215473)[0m 2024-07-20 20:59:02.202336: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[36m(EnvironmentLoop pid=2215475)[0m 2024-07-20 20:59:02.520913: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[36m(EnvironmentLoop pid=2216787)[0m 2024-07-20 20:59:07.639959: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected[32m [repeated 17x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(EnvironmentLoop pid=2220055)[0m 2024-07-20 20:59:12.731303: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected[32m [repeated 20x across cluster][0m
[36m(EnvironmentLoop pid=2215475)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.
[36m(EnvironmentLoop pid=2215475)[0m Instructions for updating:
[36m(EnvironmentLoop pid=2215475)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.
[36m(EnvironmentLoop pid=2215475)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.
[36m(EnvironmentLoop pid=2215475)[0m Instructions for updating:
[36m(EnvironmentLoop pid=2215475)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.
[36m(EnvironmentLoop pid=2215475)[0m 2024-07-20 20:59:16.517341: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
[36m(EnvironmentLoop pid=2224053)[0m 2024-07-20 20:59:17.812996: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected[32m [repeated 21x across cluster][0m
[36m(EnvironmentLoop pid=2216105)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.[32m [repeated 26x across cluster][0m
[36m(EnvironmentLoop pid=2216105)[0m Instructions for updating:[32m [repeated 26x across cluster][0m
[36m(EnvironmentLoop pid=2216105)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.[32m [repeated 26x across cluster][0m
[36m(EnvironmentLoop pid=2216048)[0m 2024-07-20 20:59:20.599295: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.[32m [repeated 12x across cluster][0m
[36m(EnvironmentLoop pid=2224377)[0m 2024-07-20 20:59:17.850984: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[36m(EnvironmentLoop pid=2220055)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.[32m [repeated 28x across cluster][0m
[36m(EnvironmentLoop pid=2220055)[0m Instructions for updating:[32m [repeated 28x across cluster][0m
[36m(EnvironmentLoop pid=2220055)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.[32m [repeated 28x across cluster][0m
[36m(EnvironmentLoop pid=2220055)[0m 2024-07-20 20:59:27.055689: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.[32m [repeated 15x across cluster][0m
[36m(Learner pid=2215121)[0m /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:522: UserWarning: Encoding a StructuredValue with type tensorflow_probability.python.distributions.independent.Independent_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
[36m(Learner pid=2215121)[0m   warnings.warn("Encoding a StructuredValue with type %s; loading this "
[36m(Learner pid=2215121)[0m /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:522: UserWarning: Encoding a StructuredValue with type tfp.distributions.Normal_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
[36m(Learner pid=2215121)[0m   warnings.warn("Encoding a StructuredValue with type %s; loading this "
[36m(EnvironmentLoop pid=2224377)[0m WARNING:tensorflow:From /root/anaconda3/envs/flybody/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py:342: calling _Independent.__init__ (from tensorflow_probability.python.distributions.independent) with reinterpreted_batch_ndims=None is deprecated and will be removed after 2022-03-01.[32m [repeated 66x across cluster][0m
[36m(EnvironmentLoop pid=2224377)[0m Instructions for updating:[32m [repeated 66x across cluster][0m
[36m(EnvironmentLoop pid=2224377)[0m Please pass an integer value for `reinterpreted_batch_ndims`. The current behavior corresponds to `reinterpreted_batch_ndims=tf.size(distribution.batch_shape_tensor()) - 1`.[32m [repeated 66x across cluster][0m
[36m(EnvironmentLoop pid=2224377)[0m 2024-07-20 20:59:29.793567: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.[32m [repeated 33x across cluster][0m
